{{- if .Values.metricsClusterRoleEnabled }}
{{- $fullName := include "ssm-param-injector.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullName }}-metrics-reader
  labels:
    {{- include "ssm-param-injector.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end }}
